--========================================================
-- magnitude analysis
-- compares measures value by categories/dimensions
-- helps to understand the importance of different categories
--========================================================

--Total Customers by countries
SELECT 
country,
COUNT(customer_id) Total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_customers DESC

--Customers by gender
SELECT 
gender,
COUNT(customer_id) as customers_by_gender
FROM gold.dim_customers
GROUP BY gender
order by customers_by_gender DESC

--split of products by category
SELECT 
category,
COUNT(product_id) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--average cost in each category
SELECT 
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--total revenue generated by each category
SELECT 
p.category,
SUM(s.sales_amount) as total_revenue
FROM gold.dim_products p
RIGHT JOIN 
gold.fact_sales s ON s.product_key=p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- TOTAL revenue generated by each costomer
SELECT 
c.customer_id,
C.first_name,
C.last_name,
SUM(s.sales_amount) AS  revenue_by_customer
FROM gold.fact_sales s
LEFT JOIN
gold.dim_customers c ON c.customer_key=s.customer_key
GROUP BY 
customer_id,
C.first_name,
C.last_name
ORDER BY revenue_by_customer DESC

-- Distribution of sold items across countries
SELECT 
c.country,
COUNT(s.product_key) AS country_sales
FROM gold.fact_sales s
LEFT JOIN
gold.dim_customers c ON c.customer_key=s.customer_key
GROUP BY c.country
ORDER BY country_sales DESC
